author: Dr. Pepper
heading: "Golem #420"
title: "How to outsmart a clanker - a lecture in LLM manipulation, serious threats and numerous other tricks"

date: 19th march 2026
place: WEiTI, room 133
time: 18:15
